//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public int PId { get; set; }
        public string Name { get; set; }
        public int Contact { get; set; }
        public int EventId { get; set; }
    }
}
